sudo: required

language: c

services:
  - docker

before_install:
  - docker info
  - docker build -t stakater/java8-alpine .

script:
  - docker run -it --rm stakater/java8-alpine java -version
  - docker run -it --rm stakater/java8-alpine java -version